/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_army_libjpeg_JpegUtils */

#ifndef _Included_com_army_libjpeg_JpegUtils
#define _Included_com_army_libjpeg_JpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_army_libjpeg_JpegUtils
 * Method:    compressBitmap
 * Signature: (Landroid/graphics/Bitmap;III[BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_army_libjpeg_JpegUtils_compressBitmap
  (JNIEnv *, jclass, jobject, jint, jint, jint, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
